server:
  port: 80
spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/personnel_db?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#  ssl:
#  #证书路径
#    key-store: tomcat.key
#    key-store-type: JKS
#    key-alias: tomcat
#  # 配置密码，就是在生成证书的时候输入的密码
#    key-store-password: 123456

  

