server:
  port: 8761
#  ssl:
#    #证书路径
#      key-store: tomcat.key
#      key-store-type: JKS
#      key-alias: tomcat
#    # 配置密码，就是在生成证书的时候输入的密码
#      key-store-password: 123456


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    